(() => {
  'use strict';
  const KEY='stride-health-v1', $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const dateKey=(d=new Date())=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const dateFrom=k=>new Date(`${k}T12:00:00`), addDays=(d,n)=>{d=new Date(d);d.setDate(d.getDate()+n);return d}, clamp=(n,a,b)=>Math.min(b,Math.max(a,n)), round=(n,s=1)=>Math.round(n/s)*s;
  const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`, esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const foods=[
    ['Greek yogurt & berries','1 bowl · 1 cup yogurt',210,23,25,2,'🥣','Breakfast'],['Eggs & whole grain toast','2 eggs · 2 slices',330,20,30,14,'🍳','Breakfast'],['Protein oatmeal','1 bowl',390,30,48,9,'🥣','Breakfast'],
    ['Chicken rice bowl','1 bowl · 5 oz chicken',540,48,58,13,'🍚','Lunch'],['Turkey sandwich','1 sandwich',410,32,43,12,'🥪','Lunch'],['Tuna salad wrap','1 wrap',390,35,34,13,'🌯','Lunch'],
    ['Salmon, potato & greens','1 plate · 5 oz salmon',570,43,45,23,'🐟','Dinner'],['Lean beef taco bowl','1 bowl',610,45,62,20,'🥗','Dinner'],['Chicken pasta & vegetables','1 plate',620,49,72,16,'🍝','Dinner'],
    ['Protein shake','1 scoop with milk',220,31,16,4,'🥤','Snacks'],['Apple & peanut butter','1 apple · 1 tbsp',190,4,29,8,'🍎','Snacks'],['Cottage cheese','1 cup',220,28,9,8,'🥛','Snacks'],['Banana','1 medium',105,1,27,0,'🍌','Snacks'],['Almonds','1 oz',165,6,6,14,'🥜','Snacks']
  ].map(([name,serving,calories,protein,carbs,fat,emoji,meal])=>({name,serving,calories,protein,carbs,fat,emoji,meal}));
  const ex={
    gym:{A:[['Goblet squat','3 × 8–10'],['Dumbbell bench press','3 × 8–12'],['Lat pulldown','3 × 8–12'],['Romanian deadlift','3 × 8–10'],['Plank','3 × 30–45 sec']],B:[['Leg press','3 × 10–12'],['Seated cable row','3 × 8–12'],['Dumbbell shoulder press','3 × 8–10'],['Hip thrust','3 × 10–12'],['Dead bug','3 × 8/side']],C:[['Trap-bar deadlift','3 × 6–8'],['Incline dumbbell press','3 × 8–12'],['Assisted pull-up','3 × 6–10'],['Reverse lunge','3 × 8/side'],['Farmer carry','3 × 30 sec']],D:[['Hack squat','3 × 8–10'],['Chest-supported row','3 × 8–12'],['Machine chest press','3 × 8–12'],['Leg curl','3 × 10–15'],['Pallof press','3 × 10/side']]},
    home:{A:[['Chair squat','3 × 10–15'],['Incline push-up','3 × 6–12'],['Backpack row','3 × 10–15'],['Glute bridge','3 × 12–15'],['Plank','3 × 20–40 sec']],B:[['Reverse lunge','3 × 8/side'],['Knee or floor push-up','3 × 6–12'],['Single-arm backpack row','3 × 10/side'],['Backpack Romanian deadlift','3 × 10–15'],['Dead bug','3 × 8/side']],C:[['Tempo squat','3 × 10–15'],['Pike push-up','3 × 6–10'],['Towel isometric row','3 × 20–30 sec'],['Single-leg glute bridge','3 × 8/side'],['Side plank','3 × 20 sec/side']],D:[['Split squat','3 × 8/side'],['Close-grip push-up','3 × 6–12'],['Backpack row','3 × 12–15'],['Single-leg RDL','3 × 8/side'],['Suitcase carry','3 × 30 sec/side']]}
  };
  const hard={
    gym:{A:[['Back squat','4 x 5-6'],['Romanian deadlift','4 x 8'],['Walking lunge','3 x 10/side'],['Leg press','3 x 12'],['Hanging knee raise','3 x 12'],['Bike sprint finisher','6 x 20 sec hard / 70 sec easy']],B:[['Bench press','4 x 5-6'],['Weighted or assisted pull-up','4 x 6-8'],['Incline dumbbell press','3 x 10'],['Chest-supported row','3 x 10'],['Lateral raise','3 x 15'],['Rower finisher','6 x 30 sec hard / 60 sec easy']],C:[['Dynamic warm-up','6 minutes'],['Kettlebell swing','5 x 15'],['Sled push or incline walk','8 x 30 sec'],['Battle rope interval','6 x 20 sec'],['Farmer carry','4 x 40 sec'],['Mobility cooldown','8 minutes']],D:[['Trap-bar deadlift','4 x 4-6'],['Front squat','3 x 8'],['Hip thrust','4 x 10'],['Bulgarian split squat','3 x 8/side'],['Leg curl','3 x 12'],['Incline treadmill','10 minutes steady']],E:[['Overhead press','4 x 6'],['Barbell or cable row','4 x 8'],['Dumbbell bench press','3 x 10'],['Lat pulldown','3 x 10'],['Curl + pressdown superset','3 x 12 each'],['Ski erg finisher','8 x 20 sec hard / 40 sec easy']]},
    home:{A:[['Loaded backpack squat','4 x 8'],['Backpack Romanian deadlift','4 x 10'],['Reverse lunge','3 x 10/side'],['Single-leg glute bridge','3 x 12/side'],['Hollow hold','3 x 30 sec'],['Fast step-up finisher','6 x 30 sec / 60 sec easy']],B:[['Tempo push-up','4 x 8-15'],['Single-arm backpack row','4 x 10/side'],['Pike push-up','3 x 8-12'],['Floor press','3 x 12'],['Backpack curl + close push-up','3 x 12 each'],['Mountain climber finisher','6 x 20 sec / 60 sec easy']],C:[['Dynamic warm-up','6 minutes'],['Backpack swing or hinge','5 x 15'],['High-knee march','8 x 30 sec'],['Shadow boxing','6 x 30 sec'],['Suitcase carry','4 x 40 sec/side'],['Mobility cooldown','8 minutes']],D:[['Rear-foot elevated split squat','4 x 8/side'],['Single-leg RDL','4 x 8/side'],['Tempo squat','3 x 15'],['Hamstring walkout','3 x 10'],['Calf raise','4 x 15'],['Brisk hill walk','10 minutes steady']],E:[['Feet-elevated push-up','4 x 8-12'],['Backpack row','4 x 12'],['Pike push-up','3 x 10'],['Towel row isometric','3 x 30 sec'],['Backpack curl + triceps extension','3 x 12 each'],['Burpee step-back finisher','6 x 20 sec / 60 sec easy']]}
  };
  const blank=()=>({version:3,profile:null,targets:null,foods:{},weights:[],workouts:{},tasks:{},adjustments:[],performance:{},foodLibrary:{recipes:[],customFoods:[],recents:[],draft:null,quickTray:[],remoteCache:{}},createdAt:null});
  let envelope=null,cryptoKey=null,cryptoSalt=null,legacyData=false,saveChain=Promise.resolve();
  let state=load(),selected=dateKey(),range=30,step=1,toastTimer,pinAutoTimer,foodLibrarySaveTimer,cloudClient=null,cloudUser=null,cloudPushTimer=null,cloudAuthMode='signin';
  function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return blank();const data=JSON.parse(raw);if(data.encrypted){envelope=data;return blank()}legacyData=!!data.profile;return{...blank(),...data}}catch{return blank()}}
  const toB64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))),fromB64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
  async function deriveKey(pin,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
  function save(){if(!cryptoKey||!cryptoSalt)return Promise.resolve();const snapshot=JSON.stringify(state),key=cryptoKey,salt=new Uint8Array(cryptoSalt);saveChain=saveChain.then(async()=>{const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(snapshot)),packed={encrypted:true,version:2,salt:toB64(salt),iv:toB64(iv),data:toB64(cipher),updatedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(packed));queueCloudPush(packed)});return saveChain}
  function targets(p){const kg=p.currentWeight*.453592,cm=(p.heightFt*12+p.heightIn)*2.54,bmr=10*kg+6.25*cm-5*p.age+(p.sex==='male'?5:-161),maintenance=bmr*Number(p.activity),floor=p.sex==='male'?1500:1200,calories=round(clamp(maintenance-Number(p.pace)*500,floor,maintenance-150),25),protein=round(clamp(kg*1.8,90,220),5),fat=round(calories*.27/9,5),carbs=Math.max(50,round((calories-protein*4-fat*9)/4,5));return{calories,protein,fat,carbs,maintenance:round(maintenance,25),bmr:round(bmr)}}
  function init(){installPinGuards();bind();render();if(envelope)showPin('unlock');else if(legacyData)showPin('create');else if(!state.profile)openModal('onboardingModal');initCloud();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
  function installPinGuards(){$$('#unlockPin,#unlockPinConfirm,input[name="pin"],input[name="pinConfirm"]').forEach(input=>{input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'').slice(0,6)});input.addEventListener('beforeinput',e=>{if(e.data&&/\D/.test(e.data))e.preventDefault()})})}
  function bind(){
    $$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-open-settings],#settingsBtn').forEach(b=>b.onclick=openSettings);$$('[data-open-log]').forEach(b=>b.onclick=()=>{nav('log');logTab(b.dataset.openLog)});
    $('#coachAction').onclick=coachAction;$('#onboardingNext').onclick=nextStep;$('#onboardingBack').onclick=()=>showStep(step-1);$('#onboardingForm').onsubmit=finishSetup;
    $$('[data-log-tab]').forEach(b=>b.onclick=()=>logTab(b.dataset.logTab));$('#addFoodBtn').onclick=()=>openSheet('foodSheet');$('#addWeightBtn').onclick=openWeight;$('#foodSearch').oninput=e=>foodResults(e.target.value);$('#customFoodBtn').onclick=()=>$('#customFoodForm').classList.toggle('hidden');$('#customFoodForm').onsubmit=customFood;$('#weightForm').onsubmit=addWeight;
    $$('[data-close-sheet]').forEach(b=>b.onclick=closeSheets);$$('.sheet-overlay').forEach(x=>x.onclick=e=>{if(e.target===x)closeSheets()});
    $('#weekStrip').onclick=e=>{const b=e.target.closest('[data-date]');if(b){selected=b.dataset.date;renderPlan()}};$('#exerciseList').onchange=exerciseCheck;$$('[data-output]').forEach(b=>b.onclick=()=>setOutput(b.dataset.output));$('#recalculateWorkoutBtn').onclick=()=>recalculateWorkout(true);$('#workoutCompleteBtn').onclick=completeWorkout;$('#taskList').onchange=taskCheck;$('#mealList').onclick=removeFood;$('#weightHistory').onclick=removeWeight;
    $('#settingsForm').onsubmit=saveSettings;$('#resetDataBtn').onclick=resetData;$('#pinForm').onsubmit=handlePin;$('#unlockPin').oninput=pinAutoUnlock;$('#forgotPinBtn').onclick=forgotPin;$('#lockAppBtn').onclick=lockApp;$('#restoreCloudBtn').onclick=openCloud;$('#pinCloudRestoreBtn').onclick=openCloud;$('#cloudConnectBtn').onclick=openCloud;$('#cloudSyncNowBtn').onclick=()=>cloudReconcile(true);$('#cloudSignOutBtn').onclick=cloudSignOut;$('#cloudAuthForm').onsubmit=handleCloudAuth;$$('[data-auth-mode]').forEach(b=>b.onclick=()=>setCloudAuthMode(b.dataset.authMode));$('#cloudForgotPassword').onclick=sendPasswordReset;$$('#rangeSwitch button').forEach(b=>b.onclick=()=>{range=b.dataset.range==='all'?'all':Number(b.dataset.range);$$('#rangeSwitch button').forEach(x=>x.classList.toggle('active',x===b));renderProgress()});$('#applyAdjustmentBtn').onclick=applyAdjustment;
    window.onhashchange=()=>nav(location.hash.slice(1)||'today',false)
  }
  function nav(view,hash=true){if(!['today','plan','log','progress'].includes(view))view='today';$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(hash)history.replaceState(null,'',`#${view}`);scrollTo(0,0);if(view==='plan')renderPlan();if(view==='log')renderLog();if(view==='progress')renderProgress()}
  function openModal(id){const x=$('#'+id);x.classList.add('open');x.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function openSheet(id){closeSheets();const x=$('#'+id);x.classList.add('open');x.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(id==='foodSheet'){foodResults('');setTimeout(()=>$('#foodSearch').focus(),80)}}
  function closeSheets(){$$('.sheet-overlay').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')});document.body.style.overflow=''}
  function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('show'),2200)}
  function showPin(mode){const form=$('#pinForm'),create=mode==='create';form.dataset.mode=mode;form.reset();$('#pinError').classList.add('hidden');$('#pinTitle').textContent=create?'Secure your existing data.':'Welcome back.';$('#pinCopy').textContent=create?'Choose a 6-digit PIN to encrypt the plan already stored in this browser.':'Enter your PIN to decrypt your plan and health data on this device.';$('#pinConfirmLabel').classList.toggle('hidden',!create);$('#unlockPinConfirm').required=create;$('#unlockBtn').textContent=create?'Encrypt my data':'Unlock TruFit';$('#forgotPinBtn').classList.toggle('hidden',create);openModal('pinModal');setTimeout(()=>$('#unlockPin').focus(),100)}
  function pinAutoUnlock(e){clearTimeout(pinAutoTimer);if($('#pinForm').dataset.mode==='unlock'&&e.target.value.length===6)pinAutoTimer=setTimeout(()=>$('#pinForm').requestSubmit($('#unlockBtn')),220)}
  async function handlePin(e){e.preventDefault();const pin=$('#unlockPin').value,mode=e.target.dataset.mode,error=$('#pinError'),btn=$('#unlockBtn');clearTimeout(pinAutoTimer);if(btn.disabled)return;error.classList.add('hidden');if(mode==='create'&&pin!==$('#unlockPinConfirm').value){error.textContent='Those PINs do not match.';error.classList.remove('hidden');return}btn.disabled=true;btn.textContent=mode==='create'?'Encrypting…':'Decrypting your plan…';try{if(mode==='create'){cryptoSalt=crypto.getRandomValues(new Uint8Array(16));cryptoKey=await deriveKey(pin,cryptoSalt);legacyData=false;await save()}else{if(!envelope?.salt||!envelope?.iv||!envelope?.data)throw new Error('missing encrypted data');const salt=fromB64(envelope.salt),candidate=await deriveKey(pin,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(envelope.iv)},candidate,fromB64(envelope.data));state={...blank(),...JSON.parse(new TextDecoder().decode(plain))};cryptoSalt=salt;cryptoKey=candidate;envelope=null}$('#pinModal').classList.remove('open');$('#pinModal').setAttribute('aria-hidden','true');document.body.style.overflow='';render();toast(mode==='create'?'Your data is encrypted':'Plan decrypted · welcome back')}catch{$('#pinModal .pin-modal').classList.remove('unlock-error');void $('#pinModal .pin-modal').offsetWidth;$('#pinModal .pin-modal').classList.add('unlock-error');error.textContent=envelope?'That PIN could not decrypt this backup. Check all six digits or restore with email.':'No encrypted backup is loaded. Restore with email first.';error.classList.remove('hidden');$('#unlockPin').select()}finally{btn.disabled=false;btn.textContent=mode==='create'?'Encrypt my data':'Unlock TruFit'}}
  async function lockApp(){closeSheets();await saveChain;try{envelope=JSON.parse(localStorage.getItem(KEY))}catch{envelope=null}cryptoKey=null;cryptoSalt=null;state=blank();render();showPin('unlock')}
  function forgotPin(){if(!confirm('Without the PIN, encrypted data cannot be recovered. Reset everything and start over?'))return;localStorage.removeItem(KEY);envelope=null;cryptoKey=null;cryptoSalt=null;legacyData=false;state=blank();$('#pinModal').classList.remove('open');document.body.style.overflow='';render();showStep(1);openModal('onboardingModal')}
  function nextStep(){const inputs=$$('input,select',$(`.form-step[data-step="${step}"]`));if(!inputs.every(i=>i.reportValidity()))return;showStep(step+1)}
  function showStep(n){step=clamp(n,1,3);$$('.form-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===step));$$('.step-dots i').forEach((d,i)=>d.classList.toggle('active',i===step-1));$('#onboardingBack').classList.toggle('hidden',step===1);$('#onboardingNext').classList.toggle('hidden',step===3);$('#onboardingFinish').classList.toggle('hidden',step!==3)}
  async function finishSetup(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.pin!==d.pinConfirm){e.target.elements.pinConfirm.setCustomValidity('PINs must match');e.target.elements.pinConfirm.reportValidity();return}e.target.elements.pinConfirm.setCustomValidity('');if(d.experience==='beginner'&&d.trainingMode!=='sustainable'&&!confirm('High-output protocols are not recommended for new or returning trainees. Continue anyway?'))return;const btn=$('#onboardingFinish');btn.disabled=true;btn.textContent='Encrypting your plan…';try{const p={name:d.name.trim(),age:+d.age,sex:d.sex,heightFt:+d.heightFt,heightIn:+d.heightIn,currentWeight:+d.currentWeight,goalWeight:+d.goalWeight,activity:+d.activity,pace:+d.pace,experience:d.experience,equipment:d.equipment,trainingMode:d.trainingMode||'sustainable',trainingDays:+d.trainingDays,coaching:true};state.profile=p;state.targets=targets(p);state.createdAt=dateKey();state.weights=[{id:uid(),date:dateKey(),weight:p.currentWeight}];cryptoSalt=crypto.getRandomValues(new Uint8Array(16));cryptoKey=await deriveKey(d.pin,cryptoSalt);await save();$('#onboardingModal').classList.remove('open');document.body.style.overflow='';e.target.reset();render();toast('Your encrypted TruFit plan is ready')}catch{toast('Encryption is unavailable in this browser')}finally{btn.disabled=false;btn.textContent='Build my plan'}}
  function render(){renderToday();renderPlan();renderLog();renderProgress();nav(location.hash.slice(1)||'today',false)}
  function totals(k=dateKey()){return(state.foods[k]||[]).reduce((a,f)=>({calories:a.calories+ +f.calories,protein:a.protein+ +f.protein,carbs:a.carbs+ +f.carbs,fat:a.fat+ +f.fat}),{calories:0,protein:0,carbs:0,fat:0})}
  function schedule(){const mode=state.profile?.trainingMode||'sustainable';if(mode==='aggressive')return[[1,'A','Lower Power'],[2,'B','Upper Density'],[4,'D','Lower Volume'],[5,'E','Upper Power']];if(mode==='hybrid')return[[1,'A','Lower Power'],[2,'B','Upper Density'],[3,'C','Conditioning Grid'],[5,'D','Lower Volume'],[6,'E','Upper Power']];const n=state.profile?.trainingDays||3,days=n===2?[1,4]:n===4?[1,2,4,6]:[1,3,5];return days.map((day,i)=>[day,'ABCD'[i],`Full body ${'ABCD'[i]}`])}
  function workoutDays(){return schedule().map(x=>x[0])}
  function monday(d=new Date()){d=new Date(d);const day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return d}
  function workout(k){const item=schedule().find(x=>x[0]===(dateFrom(k).getDay()||7));if(!item)return null;const [day,key,name]=item,mode=state.profile?.trainingMode||'sustainable',isHard=mode!=='sustainable';return{key,name,hard:isHard,exercises:(isHard?hard:ex)[state.profile?.equipment||'gym'][key],duration:isHard?(key==='C'?45:55):(state.profile?.experience==='intermediate'?45:35)}}
  function weekDone(){const m=monday();return workoutDays().map(d=>dateKey(addDays(m,d-1))).filter(k=>state.workouts[k]?.complete).length}
  function streak(){let n=0;for(let i=0;i<365;i++){const k=dateKey(addDays(new Date(),-i)),active=state.foods[k]?.length||state.weights.some(w=>w.date===k)||state.workouts[k]?.complete;if(active)n++;else if(i)break}return n}
  function renderToday(){const now=new Date(),g=now.getHours()<12?'Good morning':now.getHours()<18?'Good afternoon':'Good evening';$('#dateLabel').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();$('#greeting').textContent=state.profile?`${g}, ${state.profile.name}`:g;$('#streakCount').textContent=streak();renderCoach();renderNutrition();renderWorkoutPreview();renderTasks()}
  function renderCoach(){const title=$('#coachTitle'),msg=$('#coachMessage'),a=$('#coachAction');if(!state.profile){title.textContent='Let’s build your plan.';msg.textContent='A few details will help TruFit make today simple and specific.';a.innerHTML='Get started <svg><use href="#i-chevron"/></svg>';return}const t=totals(),wo=workout(dateKey()),weighed=state.weights.some(w=>w.date===dateKey()),hour=new Date().getHours();if(!weighed&&hour<13){set('Start with a quick weigh-in.','One number cannot define progress, but consistent morning weigh-ins reveal the trend we can coach.','weight','Log weight')}else if(wo&&!state.workouts[dateKey()]?.complete){set(`Today: ${wo.name}.`,wo.hard?`High-output session: ${wo.duration} minutes. Do the written work only—no bonus sets—and stop if form or breathing breaks down.`:`Set aside ${wo.duration} minutes. Use controlled reps and finish each set with 1–3 good reps still available.`,'workout','See workout')}else if(t.protein<state.targets.protein*.5&&hour>=13){set('Make protein the next easy win.',`You have about ${Math.max(0,state.targets.protein-Math.round(t.protein))}g left today. Build your next meal around a lean protein.`,'food','Log a meal')}else if(t.calories>state.targets.calories){set('Nothing is ruined.','Log honestly, skip the punishment, and return to your usual plan at the next meal. The weekly average matters more than one day.','progress','View the trend')}else set('Keep today boring and repeatable.',`Aim for ${state.targets.calories.toLocaleString()} calories, get your planned movement, and choose foods you can happily eat again next week.`,'food','Log food');function set(t,m,action,label){title.textContent=t;msg.textContent=m;a.dataset.action=action;a.innerHTML=`${label} <svg><use href="#i-chevron"/></svg>`}}
  function coachAction(){if(!state.profile)return openModal('onboardingModal');const a=$('#coachAction').dataset.action;if(a==='weight')openWeight();else if(a==='workout')nav('plan');else if(a==='progress')nav('progress');else{nav('log');logTab('food')}}
  function renderNutrition(){const t=totals(),g=state.targets||{calories:0,protein:0,carbs:0,fat:0};$('#calRemaining').textContent=state.profile?Math.max(0,Math.round(g.calories-t.calories)).toLocaleString():'—';$('#calorieRing').style.setProperty('--progress',`${g.calories?clamp(t.calories/g.calories,0,1)*360:0}deg`);[['protein',t.protein,g.protein],['carbs',t.carbs,g.carbs],['fat',t.fat,g.fat]].forEach(([k,v,m])=>{$(`#${k}Now`).textContent=Math.round(v);$(`#${k}Goal`).textContent=m||'—';$(`#${k}Bar`).style.width=`${m?clamp(v/m*100,0,100):0}%`})}
  function renderWorkoutPreview(){const box=$('#workoutPreview');if(!state.profile){box.innerHTML='<p class="empty-meal">Your first training session will appear after setup.</p>';return}const w=workout(dateKey()),done=state.workouts[dateKey()]?.complete;if(!w){$('#workoutHeading').textContent='Recovery day';box.innerHTML=`<div class="workout-top"><div class="workout-icon"><svg><use href="#i-water"/></svg></div><button class="start-button rest-button" data-nav="plan">Plan ahead</button></div><h3 style="margin-top:14px">Walk + recover</h3><p>Take a comfortable 20–30 minute walk and let your body adapt.</p><div class="workout-meta"><span><b>20–30</b> minutes</span><span><b>Easy</b> pace</span></div>`}else{$('#workoutHeading').textContent='Your workout';box.innerHTML=`<div class="workout-top"><div class="workout-icon"><svg><use href="#i-dumbbell"/></svg></div><button class="start-button" data-nav="plan">${done?'Review':'Start'}</button></div><h3 style="margin-top:14px">${w.name}${done?' · complete':''}</h3><p>${w.exercises.slice(0,3).map(x=>x[0]).join(' · ')}</p><div class="workout-meta"><span><b>${w.duration}</b> minutes</span><span><b>${w.exercises.length}</b> exercises</span></div>`}$$('[data-nav]',box).forEach(b=>b.onclick=()=>nav(b.dataset.nav))}
  function taskDefs(){const w=workout(dateKey()),t=totals();return[{id:'weight',label:'Log today’s weight',icon:'scale',auto:state.weights.some(x=>x.date===dateKey())},{id:'food',label:'Log at least two meals',icon:'food',auto:new Set((state.foods[dateKey()]||[]).map(f=>f.meal)).size>=2},{id:'protein',label:'Reach 80% of your protein target',icon:'spark',auto:state.targets&&t.protein>=state.targets.protein*.8},{id:'movement',label:w?'Complete today’s strength session':'Take a 20-minute walk',icon:w?'dumbbell':'chart',auto:w?!!state.workouts[dateKey()]?.complete:false}]}
  function renderTasks(){const tasks=taskDefs(),m=state.tasks[dateKey()]||{},n=tasks.filter(t=>t.auto||m[t.id]).length;$('#taskCount').textContent=`${n} of ${tasks.length}`;$('#taskList').innerHTML=tasks.map(t=>`<div class="task-item ${t.auto||m[t.id]?'done':''}"><span class="task-icon"><svg><use href="#i-${t.icon}"/></svg></span><label for="task-${t.id}">${t.label}</label><input class="task-check" id="task-${t.id}" data-task="${t.id}" type="checkbox" ${t.auto||m[t.id]?'checked':''} ${t.auto?'disabled':''}></div>`).join('')}
  function taskCheck(e){if(!e.target.dataset.task)return;state.tasks[dateKey()]={...(state.tasks[dateKey()]||{}),[e.target.dataset.task]:e.target.checked};save();renderToday()}
  function renderPlan(){const p=state.profile,mode=p?.trainingMode||'sustainable',n=schedule().length,names={sustainable:`${n}-day Base Protocol`,aggressive:'Overdrive · 4 days',hybrid:'Neon Hybrid · 5 days'};$('#planLevel').textContent=mode==='sustainable'?(p?.experience==='intermediate'?'BUILD':'FOUNDATION'):'HIGH OUTPUT';$('#planName').textContent=names[mode];$('#planDescription').textContent=mode==='sustainable'?(p?.equipment==='home'?'Progressive sessions using body weight and a loaded backpack.':'Simple full-body sessions that progress with you.'):(mode==='aggressive'?'Four dense strength sessions with controlled finishers and three recovery days.':'Four strength sessions plus one dedicated conditioning grid. Two recovery days are mandatory.');$('#intensityWarning').classList.toggle('hidden',mode==='sustainable');$('#weekProgress').textContent=`${weekDone()}/${n}`;const m=monday(dateFrom(selected)),today=dateKey();$('#weekStrip').innerHTML=[0,1,2,3,4,5,6].map(i=>{const d=addDays(m,i),k=dateKey(d),w=workout(k);return`<button class="day-button ${k===selected?'active':''} ${w?'workout-day':''} ${state.workouts[k]?.complete?'complete':''}" data-date="${k}"><span>${d.toLocaleDateString(undefined,{weekday:'narrow'})}</span><b>${d.getDate()}</b></button>`}).join('');const w=workout(selected),d=dateFrom(selected);$('#selectedDayLabel').textContent=selected===today?'TODAY':d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();if(!w){$('#selectedWorkoutName').textContent='Recovery day';$('#selectedWorkoutDuration').textContent='20–30 min';$('#exerciseList').innerHTML='<article class="exercise-card"><span class="exercise-number">1</span><div class="exercise-info"><h3>Comfortable walk</h3><p>20–30 minutes · conversational pace</p></div></article><article class="exercise-card"><span class="exercise-number">2</span><div class="exercise-info"><h3>Gentle mobility</h3><p>5 minutes · hips, shoulders, ankles</p></div></article>';$('#workoutCompleteBtn').classList.add('hidden');return}$('#selectedWorkoutName').textContent=w.name;$('#selectedWorkoutDuration').textContent=`${w.duration} min`;$('#workoutCompleteBtn').classList.remove('hidden');const rec=state.workouts[selected]||{exercises:{}};$('#exerciseList').innerHTML=w.exercises.map((x,i)=>`<article class="exercise-card"><span class="exercise-number">${i+1}</span><div class="exercise-info"><h3>${esc(x[0])}</h3><p>${esc(x[1])}${w.hard?' · leave 1–2 reps in reserve':' reps · 60–90 sec rest'}</p></div><input aria-label="Mark ${esc(x[0])} complete" class="exercise-done" type="checkbox" data-exercise="${i}" ${rec.exercises?.[i]?'checked':''}></article>`).join('');$('#workoutCompleteBtn').innerHTML=`<svg><use href="#i-check"/></svg> ${rec.complete?'Workout completed':'Complete workout'}`}
  function exerciseCheck(e){if(!e.target.dataset.exercise)return;const r=state.workouts[selected]||{exercises:{}};r.exercises={...(r.exercises||{}),[e.target.dataset.exercise]:e.target.checked};state.workouts[selected]=r;save()}
  function completeWorkout(){const w=workout(selected);if(!w)return;const r=state.workouts[selected]||{exercises:{}};r.complete=!r.complete;if(r.complete)w.exercises.forEach((_,i)=>r.exercises[i]=true);state.workouts[selected]=r;save();render();nav('plan',false);toast(r.complete?'Workout complete — well done':'Workout reopened')}
  function logTab(tab){$$('[data-log-tab]').forEach(b=>b.classList.toggle('active',b.dataset.logTab===tab));$('#foodPanel').classList.toggle('active',tab==='food');$('#weightPanel').classList.toggle('active',tab==='weight')}
  function renderLog(){renderMeals();renderWeights()}
  function renderMeals(){const t=totals();$('#logCalories').textContent=Math.round(t.calories).toLocaleString();$('#logProtein').textContent=`${Math.round(t.protein)}g`;$('#logCarbs').textContent=`${Math.round(t.carbs)}g`;$('#logFat').textContent=`${Math.round(t.fat)}g`;const day=state.foods[dateKey()]||[];$('#mealList').innerHTML=['Breakfast','Lunch','Dinner','Snacks'].map(meal=>{const list=day.filter(f=>f.meal===meal),c=list.reduce((s,f)=>s+ +f.calories,0);return`<section class="meal-card"><div class="meal-head"><h3>${meal}</h3><span>${Math.round(c)} kcal</span></div>${list.length?list.map(f=>`<div class="food-entry"><div><h4>${esc(f.name)}</h4><p>${f.calories} kcal · P ${f.protein}g · C ${f.carbs}g · F ${f.fat}g</p></div><button class="remove-food" data-food-id="${f.id}" aria-label="Remove food">×</button></div>`).join(''):'<p class="empty-meal">Nothing logged yet</p>'}</section>`}).join('')}
  function foodResults(term=''){const list=foods.filter(f=>f.name.toLowerCase().includes(term.toLowerCase())).slice(0,8);$('#foodResults').innerHTML=list.map(f=>`<button class="food-result" data-i="${foods.indexOf(f)}"><span class="food-result-icon">${f.emoji}</span><span><b>${f.name}</b><small>${f.serving} · ${f.protein}g protein</small></span><strong>${f.calories} kcal</strong></button>`).join('')||'<p class="helper-copy">No match. Add a custom food below.</p>';$$('[data-i]',$('#foodResults')).forEach(b=>b.onclick=()=>addFood(foods[+b.dataset.i]))}
  function addFood(f){state.foods[dateKey()]=[...(state.foods[dateKey()]||[]),{...f,id:uid()}];save();closeSheets();render();nav('log',false);logTab('food');toast(`${f.name} added`)}
  function customFood(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));addFood({name:d.foodName,calories:+d.calories,protein:+d.protein,carbs:+d.carbs,fat:+d.fat,meal:d.meal});e.target.reset();e.target.classList.add('hidden')}
  function removeFood(e){const b=e.target.closest('[data-food-id]');if(!b)return;state.foods[dateKey()]=(state.foods[dateKey()]||[]).filter(f=>f.id!==b.dataset.foodId);save();render();nav('log',false);logTab('food')}
  function latest(){return[...state.weights].sort((a,b)=>b.date.localeCompare(a.date))[0]}
  function openWeight(){if(!state.profile)return openModal('onboardingModal');$('#weightInput').value=latest()?.weight||state.profile.currentWeight;$('#weightDate').value=dateKey();openSheet('weightSheet')}
  function addWeight(e){e.preventDefault();const weight=+$('#weightInput').value,date=$('#weightDate').value;if(!weight||!date)return;state.weights=state.weights.filter(w=>w.date!==date);state.weights.push({id:uid(),date,weight});state.weights.sort((a,b)=>a.date.localeCompare(b.date));if(date===dateKey())state.profile.currentWeight=weight;save();closeSheets();render();nav('log',false);logTab('weight');toast('Weigh-in saved')}
  function renderWeights(){const l=latest(),first=state.weights[0],change=l&&first?l.weight-first.weight:0;$('#latestWeight').textContent=l?l.weight.toFixed(1):'—';$('#weightChangeText').textContent=state.weights.length>1?`${Math.abs(change).toFixed(1)} lb ${change<=0?'down':'up'} since you began`:'Log consistently to reveal your trend.';$('#weightHistory').innerHTML=[...state.weights].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12).map(w=>`<div class="weight-row"><span>${dateFrom(w.date).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</span><strong>${w.weight.toFixed(1)} lb</strong><button data-weight-id="${w.id}" aria-label="Delete weigh-in">×</button></div>`).join('')||'<p class="empty-meal">No weigh-ins yet.</p>'}
  function removeWeight(e){const b=e.target.closest('[data-weight-id]');if(!b)return;if(state.weights.length===1)return toast('Keep at least one starting weight');state.weights=state.weights.filter(w=>w.id!==b.dataset.weightId);save();render();nav('log',false);logTab('weight')}
  function trend(days=14){let data=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));if(days!=='all')data=data.filter(w=>dateFrom(w.date)>=addDays(new Date(),-days));if(data.length<2)return null;const start=dateFrom(data[0].date),pts=data.map(w=>({x:(dateFrom(w.date)-start)/864e5,y:w.weight})),n=pts.length,sx=pts.reduce((s,p)=>s+p.x,0),sy=pts.reduce((s,p)=>s+p.y,0),sxy=pts.reduce((s,p)=>s+p.x*p.y,0),sxx=pts.reduce((s,p)=>s+p.x*p.x,0),slope=(n*sxy-sx*sy)/(n*sxx-sx*sx||1);return{data,weeklySlope:slope*7}}
  function adherence(days=14){if(!state.profile)return 0;let good=0;for(let i=0;i<days;i++){const k=dateKey(addDays(new Date(),-i)),list=state.foods[k]||[];if(list.length){const t=totals(k);if(t.calories>=state.targets.calories*.75&&t.calories<=state.targets.calories*1.15)good++}}return Math.round(good/days*100)}
  function recommendation(){if(!state.profile)return null;const tr=trend(21),recent=state.weights.filter(w=>dateFrom(w.date)>=addDays(new Date(),-21)),span=recent.length>1?(dateFrom(recent.at(-1).date)-dateFrom(recent[0].date))/864e5:0,a=adherence();if(!tr||recent.length<4||span<10)return{change:0,title:'Keep collecting data',message:'Log at least 4 weigh-ins across 10 days. We’ll use the trend—not daily noise—to guide your first adjustment.'};if(a<50)return{change:0,title:'Hold your target steady',message:'There is not enough consistently logged food yet to judge the target. Focus on honest logging for one more week.'};const desired=-state.profile.pace,actual=tr.weeklySlope;if(actual>desired+.35)return{change:-100,title:'A small adjustment may help',message:`Your trend is ${actual<0?Math.abs(actual).toFixed(1)+' lb down':actual.toFixed(1)+' lb up'} per week. Try 100 fewer daily calories for 2 weeks.`};if(actual<desired-.5)return{change:100,title:'You can ease up slightly',message:`Your trend is down ${Math.abs(actual).toFixed(1)} lb per week—faster than planned. Add 100 daily calories to support recovery.`};return{change:0,title:'Your plan is working',message:`Your trend is ${actual<=0?'down '+Math.abs(actual).toFixed(1):'up '+actual.toFixed(1)} lb per week. Hold at ${state.targets.calories.toLocaleString()} calories.`}}
  function renderProgress(){const tr=trend(range),l=latest();$('#trendWeight').textContent=l?l.weight.toFixed(1):'—';$('#trendBadge').textContent=tr?`${tr.weeklySlope<=0?'↓':'↑'} ${Math.abs(tr.weeklySlope).toFixed(1)} lb / week`:'Need more data';$('#totalChange').textContent=state.weights.length>1?`${l.weight-state.weights[0].weight>0?'+':''}${(l.weight-state.weights[0].weight).toFixed(1)} lb`:'—';$('#consistency').textContent=`${adherence()}%`;$('#workoutStat').textContent=Object.entries(state.workouts).filter(([k,v])=>v.complete&&dateFrom(k)>=addDays(new Date(),-30)).length;$('#goalDistance').textContent=state.profile&&l?`${Math.max(0,l.weight-state.profile.goalWeight).toFixed(1)} lb`:'—';chart(tr);const r=recommendation();$('#checkinTitle').textContent=r?.title||'Build your plan first';$('#checkinMessage').textContent=r?.message||'Your weekly recommendation will appear here.';$('#applyAdjustmentBtn').classList.toggle('hidden',!r?.change);$('#applyAdjustmentBtn').dataset.change=r?.change||0}
  function chart(tr){const svg=$('#weightChart');if(!tr){svg.innerHTML='<text x="300" y="115" text-anchor="middle" fill="#8b938e" font-size="13">Add two or more weigh-ins to see your trend</text>';$('#chartStart').textContent=$('#chartEnd').textContent='—';return}const data=tr.data,w=600,h=220,p=15,min=Math.min(...data.map(d=>d.weight))-1,max=Math.max(...data.map(d=>d.weight))+1,start=dateFrom(data[0].date),span=Math.max(1,(dateFrom(data.at(-1).date)-start)/864e5),x=d=>p+((dateFrom(d.date)-start)/864e5)/span*(w-p*2),y=d=>p+(max-d.weight)/(max-min)*(h-p*2),points=data.map(d=>`${x(d)},${y(d)}`).join(' '),area=`M ${x(data[0])} ${h} L ${data.map(d=>`${x(d)} ${y(d)}`).join(' L ')} L ${x(data.at(-1))} ${h} Z`;svg.innerHTML=`<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#cfe3d7" stop-opacity=".8"/><stop offset="1" stop-color="#cfe3d7" stop-opacity=".08"/></linearGradient></defs><line class="chart-grid" x1="0" y1="55" x2="600" y2="55"/><line class="chart-grid" x1="0" y1="120" x2="600" y2="120"/><line class="chart-grid" x1="0" y1="185" x2="600" y2="185"/><path class="chart-area" d="${area}"/><polyline class="chart-line" points="${points}"/>${data.map(d=>`<circle class="chart-dot" cx="${x(d)}" cy="${y(d)}" r="5"/>`).join('')}`;$('#chartStart').textContent=start.toLocaleDateString(undefined,{month:'short',day:'numeric'});$('#chartEnd').textContent=dateFrom(data.at(-1).date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}
  function applyAdjustment(){const change=+$('#applyAdjustmentBtn').dataset.change;if(!change)return;state.targets.calories=round(state.targets.calories+change,25);state.targets.fat=round(state.targets.calories*.27/9,5);state.targets.carbs=Math.max(50,round((state.targets.calories-state.targets.protein*4-state.targets.fat*9)/4,5));state.adjustments.push({date:dateKey(),change,newTarget:state.targets.calories});save();render();nav('progress',false);toast(`Target updated to ${state.targets.calories.toLocaleString()} calories`)}
  function openSettings(){if(!state.profile)return openModal('onboardingModal');const f=$('#settingsForm');f.elements.name.value=state.profile.name;f.elements.goalWeight.value=state.profile.goalWeight;f.elements.pace.value=state.profile.pace;f.elements.calorieTarget.value=state.targets.calories;f.elements.trainingMode.value=state.profile.trainingMode||'sustainable';f.elements.trainingDays.value=state.profile.trainingDays;f.elements.equipment.value=state.profile.equipment;f.elements.coaching.checked=state.profile.coaching!==false;openSheet('settingsSheet')}
  function saveSettings(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),old=state.targets.calories;if((d.trainingMode==='aggressive'||d.trainingMode==='hybrid')&&state.profile.experience==='beginner'&&!confirm('High-output protocols are not recommended for new or returning trainees. Apply anyway?'))return;state.profile={...state.profile,name:d.name.trim(),goalWeight:+d.goalWeight,pace:+d.pace,trainingMode:d.trainingMode,trainingDays:+d.trainingDays,equipment:d.equipment,coaching:e.target.elements.coaching.checked};state.targets=targets(state.profile);state.targets.calories=+d.calorieTarget||old;state.targets.fat=round(state.targets.calories*.27/9,5);state.targets.carbs=Math.max(50,round((state.targets.calories-state.targets.protein*4-state.targets.fat*9)/4,5));save();closeSheets();render();toast('TruFit protocol updated')}
  function resetData(){if(!confirm('Reset your profile, logs, weigh-ins, and workouts? This cannot be undone.'))return;localStorage.removeItem(KEY);state=blank();envelope=null;cryptoKey=null;cryptoSalt=null;legacyData=false;closeSheets();render();showStep(1);openModal('onboardingModal')}
  function exerciseKind(name,prescription){
    const n=name.toLowerCase(),rx=parsePrescription(prescription);
    if(/finisher|sprint|rower|erg|bike|treadmill|hill walk|step-up|mountain climber|conditioning|high-knee|shadow boxing|sled|battle rope|brisk|burpee/.test(n))return'conditioning';
    if(/plank|dead bug|hollow|knee raise|pallof|mobility|warm-up|carry/.test(n))return'core';
    if(state.profile?.equipment==='home'||/push-up|bodyweight|single-leg glute|towel/.test(n))return'bodyweight';
    if(rx&&rx.high<=8&&/squat|deadlift|bench|press|pull-up|row/.test(n))return'strength';
    return'hypertrophy';
  }
  function parsePrescription(text){const m=String(text).match(/(\d+)\s*[x×]\s*(\d+)(?:\s*[-–]\s*(\d+))?/i);return m?{sets:+m[1],low:+m[2],high:+(m[3]||m[2])}:null}
  function adjustedPrescription(base,type,output){
    if(output==='standard')return base;
    const rx=parsePrescription(base);
    if(output==='deload'){
      if(type==='conditioning')return`${base} · cut total work 30%`;
      if(rx)return`${Math.max(2,rx.sets-1)} x ${rx.low}${rx.high!==rx.low?`-${rx.high}`:''} · use 85–90% usual load`;
      return`${base} · easy technique pace`;
    }
    if(type==='strength')return`${base} · add no more than 2.5–5% load`;
    if(type==='conditioning')return`${base} · add 1 interval or 5% time`;
    if(rx)return`${rx.sets+1} x ${rx.low}${rx.high!==rx.low?`-${rx.high}`:''} · added volume`;
    return`${base} · add one controlled round`;
  }
  function outputGuidance(level){return{deload:'Recovery-biased: one fewer set, reduced load, and no hard finisher. Technique should feel crisp.',standard:'Planned volume and load. Finish most working sets with 1–3 reps in reserve.',push:'Capped overload: at most one extra set or 5% load. Do not use Push after poor sleep, pain, or two hard days in a row.'}[level]}
  function exerciseLogFields(type,index,log){
    if(type==='conditioning')return`<div class="exercise-log"><label>Actual<input data-exercise="${index}" data-log="actual" type="number" min="0" step="1" inputmode="decimal" value="${log.actual??''}" placeholder="0"></label><label>Unit<select data-exercise="${index}" data-log="unit"><option value="rounds" ${log.unit==='rounds'?'selected':''}>Rounds</option><option value="minutes" ${log.unit==='minutes'?'selected':''}>Minutes</option></select></label><label>Effort<select data-exercise="${index}" data-log="effort"><option value="easy" ${log.effort==='easy'?'selected':''}>Easy</option><option value="target" ${!log.effort||log.effort==='target'?'selected':''}>Target</option><option value="max" ${log.effort==='max'?'selected':''}>Max</option></select></label></div>`;
    const loadLabel=type==='bodyweight'||type==='core'?'Extra lb':'Load lb';
    return`<div class="exercise-log"><label>${loadLabel}<input data-exercise="${index}" data-log="load" type="number" min="0" step="2.5" inputmode="decimal" value="${log.load??''}" placeholder="0"></label><label>Best reps<input data-exercise="${index}" data-log="reps" type="number" min="0" step="1" inputmode="numeric" value="${log.reps??''}" placeholder="0"></label><label>RIR<select data-exercise="${index}" data-log="rir">${[0,1,2,3,4].map(v=>`<option value="${v}" ${+(log.rir??2)===v?'selected':''}>${v}</option>`).join('')}</select></label></div>`;
  }
  function renderPlanV2(){
    const p=state.profile,mode=p?.trainingMode||'sustainable',n=schedule().length,names={sustainable:`${n}-day Base Protocol`,aggressive:'Overdrive · 4 days',hybrid:'Neon Hybrid · 5 days'};
    $('#planLevel').textContent=mode==='sustainable'?(p?.experience==='intermediate'?'BUILD':'FOUNDATION'):'HIGH OUTPUT';$('#planName').textContent=names[mode];$('#planDescription').textContent=mode==='sustainable'?(p?.equipment==='home'?'Progressive sessions using body weight and a loaded backpack.':'Simple full-body sessions that progress with you.'):(mode==='aggressive'?'Four dense strength sessions with controlled finishers and three recovery days.':'Four strength sessions plus one dedicated conditioning grid. Two recovery days are mandatory.');$('#intensityWarning').classList.toggle('hidden',mode==='sustainable');$('#weekProgress').textContent=`${weekDone()}/${n}`;
    const m=monday(dateFrom(selected)),today=dateKey();$('#weekStrip').innerHTML=[0,1,2,3,4,5,6].map(i=>{const d=addDays(m,i),k=dateKey(d),w=workout(k);return`<button class="day-button ${k===selected?'active':''} ${w?'workout-day':''} ${state.workouts[k]?.complete?'complete':''}" data-date="${k}"><span>${d.toLocaleDateString(undefined,{weekday:'narrow'})}</span><b>${d.getDate()}</b></button>`}).join('');
    const w=workout(selected),d=dateFrom(selected),rec=state.workouts[selected]||{exercises:{},logs:{},intensity:'standard'};$('#selectedDayLabel').textContent=selected===today?'TODAY':d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase();
    $('#outputConsole').classList.toggle('hidden',!w);$('#recalculateWorkoutBtn').classList.toggle('hidden',!w);$('#workoutCompleteBtn').classList.toggle('hidden',!w);
    if(!w){$('#selectedWorkoutName').textContent='Recovery day';$('#selectedWorkoutDuration').textContent='20–30 min';$('#exerciseList').innerHTML='<article class="exercise-card"><span class="exercise-number">1</span><div class="exercise-info"><h3>Comfortable walk</h3><p>20–30 minutes · conversational pace</p></div></article><article class="exercise-card"><span class="exercise-number">2</span><div class="exercise-info"><h3>Gentle mobility</h3><p>5 minutes · hips, shoulders, ankles</p></div></article>';return}
    const output=rec.intensity||'standard';$$('[data-output]').forEach(b=>b.classList.toggle('active',b.dataset.output===output));$('#outputValue').textContent=output.toUpperCase();$('#outputGuidance').textContent=outputGuidance(output);$('#selectedWorkoutName').textContent=w.name;$('#selectedWorkoutDuration').textContent=`${w.duration+(output==='push'?5:output==='deload'?-10:0)} min`;
    $('#exerciseList').innerHTML=w.exercises.map((x,i)=>{const type=exerciseKind(x[0],x[1]),key=x[0].toLowerCase().replace(/[^a-z0-9]+/g,'-'),log=rec.logs?.[i]||{},next=state.performance?.[key]?.next;return`<article class="exercise-card"><span class="exercise-number">${i+1}</span><div class="exercise-info"><span class="exercise-type">${type}</span><h3>${esc(x[0])}</h3><div class="exercise-target">${esc(adjustedPrescription(x[1],type,output))}</div></div><input aria-label="Mark ${esc(x[0])} complete" class="exercise-done" type="checkbox" data-exercise="${i}" ${rec.exercises?.[i]?'checked':''}>${exerciseLogFields(type,i,log)}${next?`<div class="next-target"><strong>NEXT TARGET</strong> · ${esc(next)}</div>`:''}</article>`}).join('');
    $('#workoutCompleteBtn').innerHTML=`<svg><use href="#i-check"/></svg> ${rec.complete?'Workout completed':'Complete workout'}`;
  }
  function exerciseCheckV2(e){const i=e.target.dataset.exercise;if(i===undefined)return;const r=state.workouts[selected]||{exercises:{},logs:{},intensity:'standard'};if(e.target.dataset.log){r.logs={...(r.logs||{})};r.logs[i]={...(r.logs[i]||{}),[e.target.dataset.log]:e.target.value}}else r.exercises={...(r.exercises||{}),[i]:e.target.checked};state.workouts[selected]=r;save()}
  function setOutput(level){const w=workout(selected);if(!w)return;const r=state.workouts[selected]||{exercises:{},logs:{}};r.intensity=level;state.workouts[selected]=r;save();renderPlanV2();toast(level==='push'?'Push mode capped at safe progression limits':level==='deload'?'Session recalculated as a deload':'Standard session restored')}
  function nextRecommendation(name,base,type,log){
    const rx=parsePrescription(base),rir=+(log.rir??2),reps=+log.reps||0,load=+log.load||0;
    if(type==='conditioning'){const actual=+log.actual||0;if(!actual)return null;const unit=log.unit||'rounds',effort=log.effort||'target',factor=effort==='easy'?1.1:effort==='target'?1.05:.9,next=unit==='rounds'?(effort==='max'?Math.max(1,actual-1):actual+1):Math.max(1,round(actual*factor));return`${next} ${unit} at controlled, repeatable effort`}
    if(!reps&&!load)return null;
    if(type==='bodyweight'||type==='core'){const next=rir>=2?reps+2:Math.max(1,reps);return`${next} quality ${type==='core'?'reps/seconds':'reps'}${load?` with ${load} lb`:''}; keep 1–2 RIR`}
    const low=rx?.low||Math.max(1,reps),high=rx?.high||Math.max(low,reps),lower=/squat|deadlift|leg press|lunge|hip thrust/.test(name.toLowerCase()),inc=lower?10:5;
    if(!load)return`Repeat ${Math.max(low,reps)} reps; enter load next time for automatic load progression`;
    if(reps<low||rir===0)return`${round(load*.95,2.5)} lb × ${low}; reduce load and rebuild clean reps`;
    if(reps>=high&&rir>=2)return`${round(load+inc,2.5)} lb × ${low}; earned load increase`;
    return`${load} lb × ${Math.min(high,Math.max(low,reps+1))}; hold load and add a rep`;
  }
  function recalculateWorkout(showMessage=true){const w=workout(selected);if(!w)return;const r=state.workouts[selected]||{logs:{}};state.performance=state.performance||{};let updated=0;w.exercises.forEach((x,i)=>{const log=r.logs?.[i]||{},type=exerciseKind(x[0],x[1]),next=nextRecommendation(x[0],x[1],type,log);if(next){const key=x[0].toLowerCase().replace(/[^a-z0-9]+/g,'-');state.performance[key]={next,type,date:selected,last:{...log}};updated++}});save();renderPlanV2();if(showMessage)toast(updated?`${updated} next-session target${updated===1?'':'s'} recalculated`:'Log actual reps, load, or conditioning work first')}
  function completeWorkoutV2(){const w=workout(selected);if(!w)return;const r=state.workouts[selected]||{exercises:{},logs:{}};r.complete=!r.complete;if(r.complete){recalculateWorkout(false);w.exercises.forEach((_,i)=>r.exercises[i]=true)}state.workouts[selected]=r;save();render();nav('plan',false);toast(r.complete?'Workout saved and progression updated':'Workout reopened')}
  function cloudHasConfig(){const c=window.TRUFIT_CLOUD;return!!(c?.url&&c?.publishableKey)}
  function cloudConfigured(){return cloudHasConfig()&&!!window.supabase?.createClient}
  function loadCloudLibrary(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
  async function initCloud(){
    if(!cloudHasConfig())return;
    try{await loadCloudLibrary()}catch{return console.warn('Cloud sync library could not load')}
    if(!cloudConfigured())return;
    $$('.cloud-only').forEach(x=>x.classList.remove('hidden'));
    try{const c=window.TRUFIT_CLOUD;cloudClient=window.supabase.createClient(c.url,c.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await cloudClient.auth.getSession();cloudUser=data.session?.user||null;updateCloudUI();if(cloudUser)await cloudReconcile(false);cloudClient.auth.onAuthStateChange((event,session)=>{cloudUser=session?.user||null;updateCloudUI();if(event==='SIGNED_IN')setTimeout(()=>cloudReconcile(false),0);if(event==='PASSWORD_RECOVERY')setTimeout(()=>openPasswordRecovery(),0)})}catch(e){console.warn('Cloud sync unavailable',e)}
  }
  function updateCloudUI(message){if(!cloudConfigured())return;const connected=!!cloudUser,status=$('#cloudSyncStatus');$('#cloudConnectBtn').classList.toggle('hidden',connected);$('#cloudSyncNowBtn').classList.toggle('hidden',!connected);$('#cloudSignOutBtn').classList.toggle('hidden',!connected);$('#cloudSyncCard').classList.toggle('synced',connected);status.textContent=message||(connected?`Connected · ${cloudUser.email}`:'Not connected');window.dispatchEvent(new CustomEvent('trufit:auth',{detail:{user:cloudUser}}))}
  function openCloud(){if(!cloudConfigured())return toast('Cloud sync is unavailable right now');resetCloudForm();openSheet('cloudSheet')}
  function resetCloudForm(){cloudAuthMode='signin';$('#cloudAuthForm').reset();$('#cloudError').classList.add('hidden');setCloudAuthMode('signin')}
  function cloudError(message){const el=$('#cloudError');el.textContent=message;el.classList.remove('hidden')}
  function setCloudAuthMode(mode){cloudAuthMode=mode;const recovery=mode==='recovery',signup=mode==='signup';$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#cloudAuthModes').classList.toggle('hidden',recovery);$('#cloudEmailLabel').classList.toggle('hidden',recovery);$('#cloudEmail').required=!recovery;$('#cloudPasswordLabel').firstChild.textContent=recovery?'New password':'Password';$('#cloudPassword').autocomplete=recovery||signup?'new-password':'current-password';$('#cloudTitle').textContent=recovery?'Choose a new password':signup?'Create your sync account':'Sign in to sync';$('#cloudAuthCopy').textContent=recovery?'Set a new password, then your encrypted backup will sync normally.':signup?'Your app already works locally. Create an account only to sync encrypted data and recipes.':'Your app works without an account. Sign in to restore or sync encrypted data and recipes.';$('#cloudAuthSubmit').textContent=recovery?'Save new password':signup?'Create account':'Sign in and sync';$('#cloudForgotPassword').classList.toggle('hidden',recovery||signup);$('#cloudError').classList.add('hidden')}
  async function handleCloudAuth(e){e.preventDefault();const btn=e.submitter,email=$('#cloudEmail').value.trim(),password=$('#cloudPassword').value;btn.disabled=true;btn.textContent='Working…';$('#cloudError').classList.add('hidden');try{if(cloudAuthMode==='recovery'){const {error}=await cloudClient.auth.updateUser({password});if(error)throw error;setCloudAuthMode('signin');toast('Password updated');closeSheets();return}if(cloudAuthMode==='signup'){const {data,error}=await cloudClient.auth.signUp({email,password,options:{emailRedirectTo:'https://vat120-wq.github.io/TruFit/'}});if(error)throw error;if(!data.session){cloudError('Account created. Check your email to confirm it, then return and sign in.');return}cloudUser=data.user}else{const {data,error}=await cloudClient.auth.signInWithPassword({email,password});if(error)throw error;cloudUser=data.user}updateCloudUI('Connected · syncing encrypted data…');await cloudReconcile(true);closeSheets()}catch(err){cloudError(err.message||'Account sign-in failed.')}finally{btn.disabled=false;btn.textContent=cloudAuthMode==='recovery'?'Save new password':cloudAuthMode==='signup'?'Create account':'Sign in and sync'}}
  async function sendPasswordReset(){const email=$('#cloudEmail').value.trim();if(!email){cloudError('Enter your email first.');$('#cloudEmail').focus();return}$('#cloudError').classList.add('hidden');const {error}=await cloudClient.auth.resetPasswordForEmail(email,{redirectTo:'https://vat120-wq.github.io/TruFit/'});if(error)return cloudError(error.message);cloudError('Password reset email sent. Open its link on this device.')}
  function openPasswordRecovery(){setCloudAuthMode('recovery');openSheet('cloudSheet');setTimeout(()=>$('#cloudPassword').focus(),100)}
  function queueCloudPush(packed){if(!cloudClient||!cloudUser)return;clearTimeout(cloudPushTimer);cloudPushTimer=setTimeout(()=>cloudPush(packed,false),1200)}
  async function cloudPush(packed,announce=true){if(!cloudClient||!cloudUser)return false;updateCloudUI('Syncing encrypted data…');const {error}=await cloudClient.from('trufit_sync').upsert({user_id:cloudUser.id,payload:packed,updated_at:packed.updatedAt||new Date().toISOString()},{onConflict:'user_id'});if(error){updateCloudUI('Sync failed · tap to retry');if(announce)toast('Cloud sync failed');console.warn(error);return false}updateCloudUI(`Synced · ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`);if(announce)toast('Encrypted plan synced');return true}
  async function cloudReconcile(announce=true){
    if(!cloudClient||!cloudUser)return;updateCloudUI('Checking cloud data…');const {data,error}=await cloudClient.from('trufit_sync').select('payload,updated_at').maybeSingle();if(error){updateCloudUI('Sync failed · tap to retry');if(announce)toast('Could not check cloud data');return}
    let local=null;try{local=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}const remote=data?.payload||null;
    if(remote&&(!local?.encrypted||Date.parse(remote.updatedAt||data.updated_at)>Date.parse(local.updatedAt||0))){localStorage.setItem(KEY,JSON.stringify(remote));envelope=remote;cryptoKey=null;cryptoSalt=null;legacyData=false;state=blank();$('#onboardingModal').classList.remove('open');closeSheets();render();showPin('unlock');updateCloudUI('Restored · enter PIN to decrypt');if(announce)toast('Encrypted plan restored from cloud');return}
    if(local?.encrypted&&(!remote||Date.parse(local.updatedAt||0)>Date.parse(remote.updatedAt||data?.updated_at||0))){await cloudPush(local,announce);return}
    updateCloudUI('Cloud and device are up to date');if(announce)toast('Already up to date')
  }
  async function cloudSignOut(){if(!cloudClient)return;await cloudClient.auth.signOut();cloudUser=null;updateCloudUI();toast('Cloud account disconnected')}
  window.TruFitFoodAPI={
    logFoods(items){if(!state.profile||!Array.isArray(items)||!items.length)return false;const normalized=items.map(f=>({id:uid(),name:f.name||'Food',serving:f.serving||'1 serving',calories:+f.calories||0,protein:+f.protein||0,carbs:+f.carbs||0,fat:+f.fat||0,meal:f.meal||'Dinner',source:f.source||'custom'}));state.foods[dateKey()]=[...(state.foods[dateKey()]||[]),...normalized];save();render();nav('log',false);logTab('food');toast(`${normalized.length} item${normalized.length===1?'':'s'} logged`);return true},
    library(){return JSON.parse(JSON.stringify(state.foodLibrary||{recipes:[],customFoods:[],recents:[],draft:null,quickTray:[],remoteCache:{}}))},
    saveLibrary(library,flush=false){state.foodLibrary=JSON.parse(JSON.stringify(library));clearTimeout(foodLibrarySaveTimer);if(flush)save();else foodLibrarySaveTimer=setTimeout(save,300);return true},
    today(){return dateKey()}
  };
  window.TruFitCloudAPI={client:()=>cloudClient,user:()=>cloudUser,open:openCloud};
  renderPlan=renderPlanV2;exerciseCheck=exerciseCheckV2;completeWorkout=completeWorkoutV2;
  init();
})();
